name: Test

on: [push]

jobs:


  testserver:
    name: Server test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install moto[server,all]
        pip install -r requirements.txt
        moto_server -H 0.0.0.0 &
        echo "wait until the server has started..."
        python -c "from time import sleep; sleep(5)"
    - name: Test with pytest
      run: |
        AWS_SECRET_ACCESS_KEY=server_secret AWS_ACCESS_KEY_ID=server_key pytest -sv testserver.py
